# Generated by Django 5.2.17 on 2026-09-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_count', models.IntegerField(default=0)),
                ('character_limit', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_snapshots', to='accounts.businesspartner')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('business_partner', 'snapshot_date')},
            },
        ),
    ]
