# Generated by Django 5.2.17 on 2026-09-07 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businesspartner_elevenlabs_agent_id'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', 'Initial / Cycle Allocation'), ('TOP_UP', 'Credit Top-Up'), ('BONUS', 'Bonus Credits'), ('DEDUCTION', 'Deduction / Correction')], default='TOP_UP', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in credits/characters')),
                ('description', models.CharField(blank=True, help_text='Reason or note for this transaction', max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='Invoice, PO, or external reference number', max_length=100)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounts.businesspartner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
