# Generated by Django 5.2.17 on 2026-09-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businesspartner_elevenlabs_agent_id'),
        ('dashboard', '0002_credittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('call_timestamp', models.DateTimeField(db_index=True)),
                ('agent_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('evaluation', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('messages', models.JSONField(blank=True, default=list)),
                ('conversation_cost', models.FloatField(default=0.0, help_text='Total conversation credit cost')),
                ('credits_llm', models.FloatField(default=0.0, help_text='LLM charge/credits')),
                ('caller_number', models.CharField(blank=True, max_length=50)),
                ('called_number', models.CharField(blank=True, max_length=50)),
                ('call_sid', models.CharField(blank=True, max_length=120)),
                ('caller_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_conversations', to='accounts.businesspartner')),
            ],
            options={
                'db_table': 'CallConversations',
                'ordering': ['-call_timestamp'],
            },
        ),
    ]
