# Generated by Django 5.2.17 on 2026-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='credit_alert_threshold',
            field=models.IntegerField(default=1000, help_text='Credit limit or alert threshold (credits)'),
        ),
    ]
