# Generated by Django 5.2.17 on 2026-09-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_businesspartner_credit_alert_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
