# Generated by Django 5.2.17 on 2026-09-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_businesspartner_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='elevenlabs_agent_id',
            field=models.CharField(blank=True, default='', help_text='11lab Agent ID', max_length=255),
        ),
    ]
