# Generated by Django 5.2.17 on 2026-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_businesspartner_elevenlabs_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='available_credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available credit balance for this partner', max_digits=12),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per minute of call conversation', max_digits=8),
        ),
    ]
